{% set name = "spatialmath-python" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialmath-python-{{ version }}.tar.gz
  sha256: 546048cf3a5d5be7865bdb4e7f9338860838af128f20c3a0b258bd8040d849cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ansitable
    - colored
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy
    - sympy
    - sphinxcontrib-jsmath
    - typing-extensions

test:
  imports:
    - spatialmath
    - spatialmath.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/spatialmath-python
  summary: Provides spatial maths capability for Python.
  dev_url: https://github.com/petercorke/spatialmath-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
