{% set name = "spatialmath-python" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialmath-python-{{ version }}.tar.gz
  sha256: 6efba23c8a67007b2ee44358f658c96d2d1f4db3196548b60535f58a533192ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ansitable
    - colored
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy
    - sympy
    - sphinxcontrib-jsmath

test:
  imports:
    - spatialmath
    - spatialmath.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/spatialmath-python
  summary: Provides spatial maths capability for Python.
  dev_url: https://github.com/petercorke/spatialmath-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
