{% set name = "spatialmath-python" %}
{% set version = "0.9.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialmath-python-{{ version }}.tar.gz
  sha256: c9acd51e38fbf1e88b5f19ad1e55316758d1c3106e89eb785a2de35fd6a80658

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ansitable
    - colored
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy
    - sympy

test:
  imports:
    - spatialmath
    - spatialmath.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/petercorke/spatialmath-python
  summary: Provides spatial maths capability for Python.
  dev_url: https://github.com/petercorke/spatialmath-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
    - petercorke
